[package]
name = "crispr_guessing_game" #crispr_guessing_game
version = "1.1.1"
edition = "2021"
description= "My first small rust project"
license= "MIT"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"